---
title: "crawling booking website"
output: html_notebook
---



```{r}
require(XML)
require(xml2)
require(rvest)
require(dplyr) 
```
#grab each page
```{r}
aa=NULL
for(i in c(1:40)){
  
    
  ii = i*15
  a = paste0("http://www.booking.com/searchresults.zh-tw.html?aid=383739&label=metatrivago-hotel-345032_xqdz-bd2ec355e10f8cdb07655aa8d1a85ae2_los-1_nrm-1_gstadt-2_gstkid-0_curr-twd_lang-zh-tw&sid=63f0b6e6fcb6150f4172201fd9efa63b&checkin=2017-05-16&checkout=2017-05-17&class_interval=1&dest_id=-2637882&dest_type=city&group_adults=2&group_children=0&highlighted_hotels=345032&hlrd=12&label_click=undef&mih=0&no_rooms=1&raw_dest_type=city&redirected=1&room1=A%2CA&sb_price_type=total&ssb=empty&rows=47&offset=", ii)
  aa = rbind(aa,a)
}
unique(length(aa))


```
```{r}
new = NULL
domain = "http://www.booking.com"
hotel = read_html(aa[1])%>%html_nodes('.sr-hotel__name')%>%html_text()
nrow(aa)
for(i in c(1:40)){
  hotel=read_html(aa[i])%>%html_nodes('.hotel_name_link.url')

  url = hotel%>%html_attr('href')
  url = gsub(domain, " ", url)

  url = paste0(domain,url)
 
  news = data.frame(url = url)
  
  new = rbind(new,news)
}
nrow(unique(new))
new = unique(new)
new[2, ]
```
```{r}
#show_reviews_tab


tab = NULL
nrow(new)
for(i in c(1:594)){
  tab[i] = gsub("#hotelTmpl","#tab-reviews",new[i,])
}
command_score =  read_html(as.character(tab[1]))%>%html_nodes("#review_list_score_distribution .review_score_value")%>%html_text()
read_html(as.character(tab[1]))%>%html_nodes("span.reviewer_country")
read_html(as.character(tab[1]))%>%html_nodes("div.review_item_review_score")%>%html_text()
```
```{r}
command_df = NULL
tab[1]
time = 1
for(i in c(68:594)){
  command_content = read_html(as.character(tab[i]))%>%html_nodes("div.review_item_review_container.lang_ltr")%>%html_text()
  for(j in c(1:15)){
    night1 = regexpr("• 入", command_content[j])
    night = substr(command_content[j], night1+5,night1+5 )
    grade1 = gregexpr("\\n[0-9]*", command_content[j])
    grades = grade1[[1]][4]
    gradee = grade1[[1]][5]
    grade = substr(command_content[j], grades+1, gradee-1)

    goale = grade1[[1]][15]
    goalss =gregexpr("•", command_content[j])
    goals = goalss[[1]][1]
    goal = substr(command_content[j],goals+2, goale-1 )
    types = goalss[[1]][2]
    typee = grade1[[1]][18]  
    type = substr(command_content[j], types+2, typee-1)
    temp_cdf = data.frame(time = time,hotel = i, id = j, night = night, grade = grade, goal = goal, type = type  )
    command_df = rbind(command_df, temp_cdf)
    time = time + 1
    if(time %% 1000 == 0){
      print(time)
    }
  }
}



command_df = command_df[c(1:8910),]
write.csv(command_df,"command_df.csv")

```




```{r}


command_content = read_html(as.character(tab[1]))%>%html_nodes("div.review_item_review_container.lang_ltr")%>%html_text()
length(command_content)
command_content[2]
night1 = regexpr("• 入", command_content[2])
night = substr(command_content[2], night1+5,night1+5 )
grade1 = gregexpr("\\n[0-9]*", command_content[2])
grades = grade1[[1]][4]
gradee = grade1[[1]][5]
grade = substr(command_content[2], grades+1, gradee-1)

goale = grade1[[1]][15]
goalss =gregexpr("•", command_content[10])
goals = goalss[[1]][1]
goal = substr(command_content[10],goals+2, goale-1 )
types = goalss[[1]][2]
command_content[2]
typee = grade1[[1]][18]  
type = substr(command_content[2], types+2, typee-1)

read_html(as.character(tab[1]))%>%html_nodes("div.review_item_reviewer")%>%html_text()
```


```{r}
levels(new$url)[1]
as.character(new$url[30])
head(url)
head(new)
nrow(new)
try = new[57,]
try
new
as.character(try)
nrow(unique(new))

```
#distance for each hot and near spot  PART2
```{r}
hotel_df2 = NULL
hotel_df2 = hotel_df2[,-1]
for(i in c(1:49)){
mod = as.character(new[i,])  
  
#name
name<-read_html(mod)%>%html_nodes('#hp_hotel_name')%>%html_text()


name
#distance


dist = read_html(mod)%>%html_nodes('.poi-list--numbered .poi-list-item__distance')%>%html_text()



dist_fcn = function(x){
  for(i in c(1:3)){
  
  if(grepl("km", dist[i]) == TRUE){
    dist[i] = gsub("km", "", dist[i])
    x[i] = as.numeric(dist[i])*1000
  }
  else{
    dist[i] = gsub("m", "", dist[i])
    x[i] = as.numeric(dist[i])
    
  }
  }
  return(x)
}


near_dist = NULL
near_dist = dist_fcn(near_dist)


dist = read_html(tt)%>%html_nodes('.popular-landmarks .poi-list-item__distance')%>%html_text()

hot_dist = NULL
hot_dist = dist_fcn(hot_dist)


hotel_temp = data.frame(name = name, near_dist1 = near_dist[1], near_dist2 = near_dist[2], near_dist3 = near_dist[3], hot_dist1 = hot_dist[1], hot_dist2 = hot_dist[2], hot_dist3 = hot_dist[3])

hotel_df2 = rbind(hotel_df2, hotel_temp)

}
hotel_df2 = unique(hotel_df2)
write.csv(hotel_df2,"hotel_df2.csv")
```

#contain number of people
```{r}


try = read_html(as.character(new[1,]))%>%html_nodes(xpath ="//span")

try1 = try[which(regexpr("標準入住",try)>0)]

try1[1]
try2 =regexpr("標準入住",try1)

substr(try1,try2+6,try2+6)



```


#begin to build the df
```{r}

new[6,]
try = read_html(as.character(new[,]))%>%html_nodes('div.hp_desc_important_facilities')%>%html_text()


nrow(unique(new))
```

```{r}
hotel_df = NULL
for(i in c(214:600)){
u = as.character(new[i,])

name<-read_html(u)%>%html_nodes('#hp_hotel_name')%>%html_text()


address<-read_html(u)%>%html_nodes('span.hp_address_subtitle.jq_tooltip')%>%html_text()




#score

score<-read_html(u)%>%html_nodes('p')%>%html_text()

clean_level<-score[which(regexpr("整潔度",score)>0)[1]+1]

comfort_level<-score[which(regexpr("舒適程度",score)>0)[1]+1]
location_level<-score[which(regexpr("住宿地點",score)>0)[1]+1]
facility_level<-score[which(regexpr("設施",score)>0)[1]+1]
service_level<-score[which(regexpr("員工素質",score)>0)[1]+1]
cp_level<-score[which(regexpr("性價比",score)>0)[1]+1]
wifi_level<-score[which(regexpr("免費 WiFi",score)>0)[1]+1]




#nearby location & star


#star<-read_html(as.character())%>%html_nodes('i.b-sprite.stars.ratings_stars_4.star_track')%>%html_text()

outside<-read_html(u)%>%html_nodes('.poi-list , .hp-surroundings-category_num-1 .poi-list-item__distance , .hp-surroundings-category_num-1 .poi-list-item__title')%>%html_text()

nearby_location<-outside[1]
hot_location = outside[2]
outside[5]
outside



try = nearby_location
#clean_fcn = function(try)
for(i in c(1:7)){
  ii = paste0(i,"~")
  if(i == 1||i ==2||i == 4||i == 6){
    try = sub("\n\n",ii,try)
  }else{
    try = sub("\n\n\n\n",ii,try)
  }
  
    

}

fir_lo = substr(try,regexpr("1~",try)+2,regexpr("2~",try)-1)
#fir_lo_dist = substr(try,regexpr("2~",try)+2,regexpr("3~",try)-1)


sec_lo = substr(try,regexpr("3~",try)+2,regexpr("4~",try)-1)
#sec_lo_dist = substr(try,regexpr("4~",try)+2,regexpr("5~",try)-1)

thir_lo = substr(try,regexpr("5~",try)+2,regexpr("6~",try)-1)
#thir_lo_dist = substr(try,regexpr("6~",try)+2,regexpr("7~",try)-1)


tran_fcn<-function(x){
  if((regexpr("km",x)>0)== TRUE){
    num = sub("km","",x)
    num = as.numeric(num)
    num = num*1000
  } else{
     num = substr("m","",x)
  }
  return(num)
}
#fir_lo_dist = tran_fcn(fir_lo_dist)
#sec_lo_dist = tran_fcn(sec_lo_dist)
#thir_lo_dist = tran_fcn(thir_lo_dist)


#hot location


try1 = hot_location

for(i in c(1:7)){
  ii = paste0(i,"~")
  if(i == 1||i ==2||i == 4||i == 6){
    try1 = sub("\n\n",ii,try1)
  }else{
    try1 = sub("\n\n\n\n",ii,try1)
  }
}


fir_hot = substr(try1,regexpr("1~",try1)+2,regexpr("2~",try1)-1)
#fir_hot_dist = substr(try1,regexpr("2~",try1)+2,regexpr("3~",try1)-1)


sec_hot = substr(try1,regexpr("3~",try1)+2,regexpr("4~",try1)-1)
#sec_hot_dist = substr(try1,regexpr("4~",try1)+2,regexpr("5~",try1)-1)

thir_hot = substr(try1,regexpr("5~",try1)+2,regexpr("6~",try1)-1)
#thir_hot_dist = substr(try1,regexpr("6~",try1)+2,regexpr("7~",try1)-1)

#fir_hot_dist = tran_fcn(fir_hot_dist)
#sec_hot_dist = tran_fcn(sec_hot_dist)
#thir_hot_dist = tran_fcn(thir_hot_dist)



is.na(pat)
t11<-read_html(u)%>%html_nodes('div p')%>%html_text()

pat = t11[which(regexpr("寵物",t11)>0)][1]

if(is.na(pat) == TRUE){
  pat = 0
}else if((regexpr("不允許",pat)<0)==TRUE){
  pat = 1
}else{
  pat = 0
}


#summary

facility = read_html(u)%>%html_nodes('div.hp_desc_important_facilities')%>%html_text()



summa = read_html(u)%>%html_nodes('div#summary')%>%html_text()



if((regexpr("迷你吧",summa)>0) == TRUE){
  minibar = 1
}else{
  minibar = 0
}

if((regexpr("自助早餐",summa) >1) == TRUE){
  self_breakf = 1
}else{
  self_breakf = 0
}

if((regexpr("平.電視|平.电视",summa) >1) == TRUE){
  flatTV = 1
}else{
  flatTV = 0
}
flatTV

if((regexpr("健身房",summa) >1) == TRUE){
  gym = 1
}else{
  gym = 0
}



if((regexpr("保險箱|保险箱",summa) >1) == TRUE){
  securityBox = 1
}else{
  securityBox = 0
}

#



if((regexpr("貨幣兌換|货币兑换",summa) >1) == TRUE){
  changeMoney = 1
}else{
  changeMoney = 0
}


if((regexpr("Spa|SPA|按摩",summa) >1) == TRUE){
  spa = 1
}else{
  spa = 0
}


if((regexpr("浴缸",summa) >1) == TRUE){
  bathtub = 1
}else{
  bathtub = 0
}

if((regexpr("停車|停车",summa) >1) == TRUE){
  parking = 1
}else{
  parking = 0
}
if((regexpr("停車場",facility)>1) == TRUE){
  parking = 1
}

if((regexpr("飯店.*餐廳|饭店.*餐厅",summa) >1) == TRUE){
  restaurant = 1
}else{
  restaurant = 0
}

if((regexpr("餐廳",facility)>1) ==TRUE){
  restaurant = 1
}

if((regexpr("禁煙.房",facility)>1) == TRUE){
  nosmokingroom = 1
}else{
  nosmokingroom = 0
}

if((regexpr("夜市",summa)>1) == TRUE){
  nightmarket = 1
}else{
  nightmarket = 0
}
#airport


  
y = regexpr("距離.{2,6}機場|距离.{2,6}机场",summa)
z = y + attr(y,"match.length")-1
airport = substr(summa,y,z)
mm = regexpr("距離|距离",airport)
airport_name = substr(airport,mm+2,mm+3) 
airport
yy = regexpr("[0-9]+",airport)
zz = yy +attr(yy,"match.length")-1
air_dist = substr(airport,yy,zz)

if(regexpr("[a-z]{6,9}",summa)>0 && regexpr("距",summa)<0){
  english = 1
}else{
  english = 0
}

#price


price = read_html(u)%>%html_nodes('.occ_no_dates , .lowest-price-formatted')%>%html_text()

price = price[which(regexpr("起",price)>0)]


price_vector = NULL
for(i in c(1:length(price))){
  yy = regexpr("[0-9]*,[0-9]*",price[i])
  zz = yy +attr(yy,"match.length")-1
  price1 = substr(price[i],yy,zz)
  price_vector = rbind(price_vector,price1)
}
min_price = min(price_vector)
max_price = max(price_vector)


hotel_df_tem = data.frame(name = name,address = address,clean_level = clean_level,comfort_level = comfort_level, facility_level = facility_level, location_level = location_level, service_level = service_level, cp_level = cp_level, wifi_level = wifi_level, pat = pat,minibar = minibar, self_breakf = self_breakf,flatTV = flatTV,gym = gym,securityBox = securityBox,changeMoney = changeMoney, spa = spa, bathtub = bathtub,parking = parking, restaurant = restaurant,  nightmarket = nightmarket, nosmokingroom = nosmokingroom , airport = airport_name, air_dist = air_dist,min_price = min_price,max_price = max_price,fir_lo = fir_lo, sec_lo = sec_lo, thir_lo = thir_lo, fir_hot = fir_hot, sec_hot = sec_hot,thir_hot = thir_hot,english = english)



hotel_df = rbind(hotel_df,hotel_df_tem)
}
head(hotel_df)
nrow(unique(hotel_df))
nrow(hotel_df)
View(hotel_df)
write.csv(hotel_df,"hotel_df.csv")
```
```{r}
length(price)
price
priceV = NULL
min = 1000000
for(i in c(1:length(price))){
  yy = regexpr("[0-9]*,[0-9]*",price[2])
  zz = yy +attr(yy,"match.length")-1
  p = substr(price[2],yy,zz)
  if(p < min){
    min = p
  }
}



```




